### ISSUE TITLE
I cannot connect to ActiveMQ

### ISSUE THREAD

**Issue by razeone** [gdaws/stompit#1]
I'm using ActiveMQ and because of some problems, I have been thinking in replace stomp-js by BenjaminWS with your module, just because it looks more advanced in programming terms.

Well, my problem is that I cann't even run the pubsub.js example, I can connect to my ActiveMQ server using stomp-js but with your script just doesn't work.

I always get this error qhen executing the code:

Error: Transport error: connect ECONNREFUSED

**Comment by aniinprni** [comment]
Still i am facing same issue i am using node 12 v. `Error: connect ECONNREFUSED 127.0.0.1:61613`. Error.isTranportError() method returning true

**Comment by nabeelahmedjh** [comment]
same
