### ISSUE TITLE
Kindly publish version 1.0.0

### ISSUE THREAD

**Issue by aknrdureegaesr** [gdaws/stompit#106]
Hello,

https://www.npmjs.com/search?q=stompit announces a version 1.0.0 , while https://github.com/gdaws/stompit/releases says 0.25.0 is the latest release and 0.26.0 also exists, but does not mention 1.0.0.

Thank you for providing fine software!

Regards, Andreas

**Comment by gdaws** [comment]
Pushed v1.0.0 tag. Thanks
