### ISSUE TITLE
Error: Unexpected ACK received for message-id [ID:b-23774631-

### ISSUE THREAD

**Issue by toindev** [gdaws/stompit#108]
`Error: Unexpected ACK received for message-id [ID:b-23774631-`

**Comment by gdaws** [comment]
The broker wasn't able to match the ACK to any previously dispatched message

**Comment by toindev** [comment]
Woah, thanks, but sorry too, this was a draft and I did not intend to open the issue. Thanks for the lib btw.

**Comment by gdaws** [comment]
Ah alright no problem. Thanks
